[project]
requirement = """
メッセージサブスクシステムを開発してください。
システムは、クライアントからのメッセージを受け入れるためにrestful apiを提供する。
加えて、クライアントへのメッセージをプッシュするために使用されるWebSocketサービスを提供する.
websocketはユーザーにメッセージをプッシュするだけでよく、restfulapiはメッセージを受け付けるだけでよい。
ユーザはapiを通じてメッセージを送信する際にgroupidを指定する必要があり、websocketサービスは指定されたgroupidを持つユーザにメッセージをプッシュする。
apiはメッセージを受け取った後、そのメッセージをメモリーのメッセージ・キューに入れ、メッセージを処理するために、モジュールを拡張可能のようにする。
拡張されたモジュールは処理したメッセージを別のメモリ内のメッセージ・キューに入れ、WebSocketサービスはこのメッセージ・キューからメッセージを取得してユーザーにプッシュする。
websocketは実現方法の一種であり、他によい方法があれば、それを使用してもよい、ただし、ここの処理でメッセージをプッシュするだけという点は変更しないでください。
ソースコードをsrcディレクトリに作成してください。
"""
language = "rust 1.79.0"
libraries = ["wrap", "tokio", "serde_json"]
comment_language = "日本語"
readme_language = "日本語"
base_path = "my_project"